name: Terraform Infrastructure

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.TERRAFORM_ROLE_ARN }}
        aws-region: us-east-2
    
    - uses: hashicorp/setup-terraform@v2
    
    - name: Terraform Init
      run: cd terraform && terraform init
    
    - name: Terraform Plan
      run: cd infrastructure/website && terraform plan
    
    - name: Terraform Apply
      run: cd terraform && terraform apply -auto-approve